# -*- coding: utf-8 -*-

# Gerenciamento centralizado de temas visuais da aplicação PRO ENG.
#
# Design system (todos os temas):
# - Bordas sólidas, sombras duras sem blur
# - Tipografia sans-serif pesada, weight 900, UPPERCASE
# - Mesmas chaves em todos os temas, variando apenas valores

# Dicionário de temas: cada tema mapeia chaves padronizadas para valores de cor/dimensão.
# Chaves esperadas:
# - bg_*: cores de fundo (app, cards, inputs)
# - accent*: cores de destaque (principal, bright, dim)
# - text*: cores de texto (primário, secundário, muted)
# - btn_*: cores específicas para botões de ação
# - shadow*: cor e offsets de sombra (dura, sem blur)
# - border_*: espessura e raio de bordas
# - font_*: famílias tipográficas para títulos e conteúdo

# Total de temas disponíveis no ciclo.
THEME_CYCLE_COUNT = 13

THEMES = {}


# ─── 1. NEO-BRUTAL: Quente, cores vibrantes, bordas pretas grossas ──────

THEMES["neo_brutalist"] = {
    "name": "neo_brutalist",
    "bg_app": "#F0EBE0",
    "bg_card": "#FFFFFF",
    "bg_card2": "#F5F0E8",
    "bg_input": "#FFFFFF",
    "glass_border": "#000000",
    "accent": "#FFE500",
    "accent_bright": "#0057FF",
    "accent_dim": "#0057FF",
    "text": "#000000",
    "text_dim": "#1A1A1A",
    "text_muted": "#333333",
    "line": "#000000",
    "line_eap": "#000000",
    "btn_add": "#00C44F",
    "btn_sib": "#0057FF",
    "btn_del": "#FF2222",
    "node_bg": "#FFFFFF",
    "node_border": "#000000",
    "node_text": "#000000",
    "toolbar_bg": "#FFE500",
    "toolbar_sep": "#000000",
    "toolbar_btn": "#FFFFFF",
    "toolbar_btn_h": "#0057FF",
    "sig_bg_l": "#FFFFFF",
    "sig_bg_r": "#FFFFFF",
    "sig_border": "#000000",
    "sig_text": "#000000",
    "btn_close_h": "#FF2222",
    "btn_win_h": "#000000",
    "shadow": "#000000",
    "shadow_offset_x": 8,
    "shadow_offset_y": 8,
    "shadow_hover_offset_x": 0,
    "shadow_hover_offset_y": 0,
    "border_width": 4,
    "border_radius": 0,
    "font_family": "'Space Grotesk', 'Arial Black', 'Segoe UI', sans-serif",
    "font_family_content": "'Space Grotesk', 'Arial Black', 'Segoe UI', sans-serif",
    "font_weight": 900,
    "font_uppercase": True,
    "block_yellow": "#FFE500",
    "block_green": "#00C44F",
    "block_blue": "#0057FF",
    "block_red": "#FF2222",
    "block_orange": "#FF6B00",
    "block_purple": "#AA00FF",
    "block_pink": "#FF3CAC",
}

# ─── 2. MIDNIGHT: Escuro profundo, ciano elétrico, bordas sólidas ──────

THEMES["midnight"] = {
    "name": "midnight",
    "bg_app": "#0A0E17",
    "bg_card": "#111827",
    "bg_card2": "#1F2937",
    "bg_input": "#1A1F2E",
    "glass_border": "#FFFFFF",
    "accent": "#00E5FF",
    "accent_bright": "#FF6D00",
    "accent_dim": "#007C91",
    "text": "#E8F5FF",
    "text_dim": "#94A3B8",
    "text_muted": "#64748B",
    "line": "#00E5FF",
    "line_eap": "#00E5FF",
    "btn_add": "#00E676",
    "btn_sib": "#00E5FF",
    "btn_del": "#FF1744",
    "node_bg": "#1A1F2E",
    "node_border": "#00E5FF",
    "node_text": "#E8F5FF",
    "toolbar_bg": "#111827",
    "toolbar_sep": "#00E5FF",
    "toolbar_btn": "#E8F5FF",
    "toolbar_btn_h": "#00E5FF",
    "sig_bg_l": "#111827",
    "sig_bg_r": "#1A1F2E",
    "sig_border": "#00E5FF",
    "sig_text": "#00E5FF",
    "btn_close_h": "#FF1744",
    "btn_win_h": "#FF6D00",
    "shadow": "#001828",
    "shadow_offset_x": 8,
    "shadow_offset_y": 8,
    "shadow_hover_offset_x": 0,
    "shadow_hover_offset_y": 0,
    "border_width": 4,
    "border_radius": 0,
    "font_family": "'JetBrains Mono', 'Consolas', 'Segoe UI', sans-serif",
    "font_family_content": "'JetBrains Mono', 'Consolas', 'Segoe UI', sans-serif",
    "font_weight": 900,
    "font_uppercase": True,
    "block_yellow": "#00E5FF",
    "block_green": "#00E676",
    "block_blue": "#448AFF",
    "block_red": "#FF1744",
    "block_orange": "#FF6D00",
    "block_purple": "#7C4DFF",
    "block_pink": "#F50057",
}

# ─── 3. EMBERS: Cinza carvão, laranja brasas, estética industrial ──────

THEMES["embers"] = {
    "name": "embers",
    "bg_app": "#1E1A17",
    "bg_card": "#2A2320",
    "bg_card2": "#332D29",
    "bg_input": "#2A2320",
    "glass_border": "#FFFFFF",
    "accent": "#FF6A00",
    "accent_bright": "#FFB300",
    "accent_dim": "#B34700",
    "text": "#F5EDE5",
    "text_dim": "#9E948A",
    "text_muted": "#6E645A",
    "line": "#FF6A00",
    "line_eap": "#FFB300",
    "btn_add": "#4CAF50",
    "btn_sib": "#FF6A00",
    "btn_del": "#FF3D00",
    "node_bg": "#332D29",
    "node_border": "#FF6A00",
    "node_text": "#F5EDE5",
    "toolbar_bg": "#2A2320",
    "toolbar_sep": "#FF6A00",
    "toolbar_btn": "#F5EDE5",
    "toolbar_btn_h": "#FFB300",
    "sig_bg_l": "#1E1A17",
    "sig_bg_r": "#2A2320",
    "sig_border": "#FF6A00",
    "sig_text": "#F5EDE5",
    "btn_close_h": "#FF3D00",
    "btn_win_h": "#FFB300",
    "shadow": "#0A0807",
    "shadow_offset_x": 8,
    "shadow_offset_y": 8,
    "shadow_hover_offset_x": 0,
    "shadow_hover_offset_y": 0,
    "border_width": 4,
    "border_radius": 0,
    "font_family": "'Roboto Mono', 'Consolas', 'Segoe UI', sans-serif",
    "font_family_content": "'Roboto Mono', 'Consolas', 'Segoe UI', sans-serif",
    "font_weight": 900,
    "font_uppercase": True,
    "block_yellow": "#FFB300",
    "block_green": "#4CAF50",
    "block_blue": "#FF6A00",
    "block_red": "#FF3D00",
    "block_orange": "#FF6A00",
    "block_purple": "#E040FB",
    "block_pink": "#FF4081",
}

# ─── 4. FOREST: Verde orgânico escuro, musgo e pinheiro ────────────────

THEMES["forest"] = {
    "name": "forest",
    "bg_app": "#0E1F12",
    "bg_card": "#142B1A",
    "bg_card2": "#1A3822",
    "bg_input": "#1A3822",
    "glass_border": "#FFFFFF",
    "accent": "#00E676",
    "accent_bright": "#76FF03",
    "accent_dim": "#007A3E",
    "text": "#E8FBE9",
    "text_dim": "#7DB87D",
    "text_muted": "#4E8250",
    "line": "#00E676",
    "line_eap": "#76FF03",
    "btn_add": "#B2FF59",
    "btn_sib": "#00E676",
    "btn_del": "#FF5252",
    "node_bg": "#1A3822",
    "node_border": "#00E676",
    "node_text": "#E8FBE9",
    "toolbar_bg": "#142B1A",
    "toolbar_sep": "#00E676",
    "toolbar_btn": "#E8FBE9",
    "toolbar_btn_h": "#76FF03",
    "sig_bg_l": "#142B1A",
    "sig_bg_r": "#1A3822",
    "sig_border": "#00E676",
    "sig_text": "#E8FBE9",
    "btn_close_h": "#FF5252",
    "btn_win_h": "#76FF03",
    "shadow": "#061009",
    "shadow_offset_x": 8,
    "shadow_offset_y": 8,
    "shadow_hover_offset_x": 0,
    "shadow_hover_offset_y": 0,
    "border_width": 4,
    "border_radius": 0,
    "font_family": "'Fira Code', 'Consolas', 'Segoe UI', sans-serif",
    "font_family_content": "'Fira Code', 'Consolas', 'Segoe UI', sans-serif",
    "font_weight": 900,
    "font_uppercase": True,
    "block_yellow": "#EEFF41",
    "block_green": "#00E676",
    "block_blue": "#00B0FF",
    "block_red": "#FF5252",
    "block_orange": "#FF9100",
    "block_purple": "#B388FF",
    "block_pink": "#FF4081",
}

# ─── 5. SYNTHWAVE: Roxo neon, magenta, retro 80s cyberpunk ──────────────

THEMES["synthwave"] = {
    "name": "synthwave",
    "bg_app": "#1A0A2E",
    "bg_card": "#2A1245",
    "bg_card2": "#351A5A",
    "bg_input": "#2A1245",
    "glass_border": "#FFFFFF",
    "accent": "#FF0090",
    "accent_bright": "#00F0FF",
    "accent_dim": "#880044",
    "text": "#F0D0FF",
    "text_dim": "#B088CC",
    "text_muted": "#7A5C9A",
    "line": "#FF0090",
    "line_eap": "#00F0FF",
    "btn_add": "#00FF87",
    "btn_sib": "#FF0090",
    "btn_del": "#FF4466",
    "node_bg": "#351A5A",
    "node_border": "#FF0090",
    "node_text": "#F0D0FF",
    "toolbar_bg": "#2A1245",
    "toolbar_sep": "#FF0090",
    "toolbar_btn": "#F0D0FF",
    "toolbar_btn_h": "#00F0FF",
    "sig_bg_l": "#1A0A2E",
    "sig_bg_r": "#2A1245",
    "sig_border": "#FF0090",
    "sig_text": "#F0D0FF",
    "btn_close_h": "#FF4466",
    "btn_win_h": "#00F0FF",
    "shadow": "#0D0517",
    "shadow_offset_x": 8,
    "shadow_offset_y": 8,
    "shadow_hover_offset_x": 0,
    "shadow_hover_offset_y": 0,
    "border_width": 4,
    "border_radius": 0,
    "font_family": "'Orbitron', 'Arial Black', 'Segoe UI', sans-serif",
    "font_family_content": "'Orbitron', 'Arial Black', 'Segoe UI', sans-serif",
    "font_weight": 900,
    "font_uppercase": True,
    "block_yellow": "#FCEE0A",
    "block_green": "#00FF87",
    "block_blue": "#00F0FF",
    "block_red": "#FF4466",
    "block_orange": "#FF6600",
    "block_purple": "#B026FF",
    "block_pink": "#FF0090",
}

# ─── 6. ARCTIC: Branco-gelo, azul glacial, minimalismo frio ────────────

THEMES["arctic"] = {
    "name": "arctic",
    "bg_app": "#EAF0F8",
    "bg_card": "#FFFFFF",
    "bg_card2": "#F0F5FC",
    "bg_input": "#FFFFFF",
    "glass_border": "#000000",
    "accent": "#2979FF",
    "accent_bright": "#00B0FF",
    "accent_dim": "#90CAF9",
    "text": "#0B1D3A",
    "text_dim": "#4A6490",
    "text_muted": "#7A9ABE",
    "line": "#2979FF",
    "line_eap": "#00B0FF",
    "btn_add": "#26C6DA",
    "btn_sib": "#2979FF",
    "btn_del": "#EF5350",
    "node_bg": "#F0F5FC",
    "node_border": "#2979FF",
    "node_text": "#0B1D3A",
    "toolbar_bg": "#FFFFFF",
    "toolbar_sep": "#2979FF",
    "toolbar_btn": "#0B1D3A",
    "toolbar_btn_h": "#00B0FF",
    "sig_bg_l": "#EAF0F8",
    "sig_bg_r": "#F0F5FC",
    "sig_border": "#2979FF",
    "sig_text": "#2979FF",
    "btn_close_h": "#EF5350",
    "btn_win_h": "#00B0FF",
    "shadow": "#B0C4D8",
    "shadow_offset_x": 8,
    "shadow_offset_y": 8,
    "shadow_hover_offset_x": 0,
    "shadow_hover_offset_y": 0,
    "border_width": 4,
    "border_radius": 0,
    "font_family": "'Inter', 'Segoe UI', 'Helvetica', sans-serif",
    "font_family_content": "'Inter', 'Segoe UI', 'Helvetica', sans-serif",
    "font_weight": 900,
    "font_uppercase": True,
    "block_yellow": "#FFD54F",
    "block_green": "#26C6DA",
    "block_blue": "#2979FF",
    "block_red": "#EF5350",
    "block_orange": "#FF8A65",
    "block_purple": "#AB47BC",
    "block_pink": "#EC407A",
}

# ─── 7. SOLAR: Amarelo-dourado, marrom-terra, estética quente suave ────

THEMES["solar"] = {
    "name": "solar",
    "bg_app": "#FFFCE8",
    "bg_card": "#FFF9D0",
    "bg_card2": "#FFEDB0",
    "bg_input": "#FFF9D0",
    "glass_border": "#000000",
    "accent": "#E65100",
    "accent_bright": "#FF8F00",
    "accent_dim": "#BF360C",
    "text": "#2D1A00",
    "text_dim": "#6B4420",
    "text_muted": "#9B7A5A",
    "line": "#E65100",
    "line_eap": "#FF8F00",
    "btn_add": "#388E3C",
    "btn_sib": "#E65100",
    "btn_del": "#C62828",
    "node_bg": "#FFF9D0",
    "node_border": "#E65100",
    "node_text": "#2D1A00",
    "toolbar_bg": "#FFF9D0",
    "toolbar_sep": "#E65100",
    "toolbar_btn": "#2D1A00",
    "toolbar_btn_h": "#FF8F00",
    "sig_bg_l": "#FFFCE8",
    "sig_bg_r": "#FFF9D0",
    "sig_border": "#E65100",
    "sig_text": "#E65100",
    "btn_close_h": "#C62828",
    "btn_win_h": "#FF8F00",
    "shadow": "#3D2B1A",
    "shadow_offset_x": 8,
    "shadow_offset_y": 8,
    "shadow_hover_offset_x": 0,
    "shadow_hover_offset_y": 0,
    "border_width": 4,
    "border_radius": 0,
    "font_family": "'Merriweather', 'Georgia', 'Segoe UI', sans-serif",
    "font_family_content": "'Merriweather', 'Georgia', 'Segoe UI', sans-serif",
    "font_weight": 900,
    "font_uppercase": True,
    "block_yellow": "#FFC107",
    "block_green": "#388E3C",
    "block_blue": "#E65100",
    "block_red": "#C62828",
    "block_orange": "#FF8F00",
    "block_purple": "#6A1B9A",
    "block_pink": "#D81B60",
}

# ─── 8. CRIMSON: Vinho profundo, vermelho escarlate, luxo ──────────────

THEMES["crimson"] = {
    "name": "crimson",
    "bg_app": "#120A0A",
    "bg_card": "#1A1111",
    "bg_card2": "#231818",
    "bg_input": "#1A1111",
    "glass_border": "#FFFFFF",
    "accent": "#FF2244",
    "accent_bright": "#FF6655",
    "accent_dim": "#990022",
    "text": "#F5E0E0",
    "text_dim": "#9B7777",
    "text_muted": "#664444",
    "line": "#FF2244",
    "line_eap": "#FF6655",
    "btn_add": "#44DD88",
    "btn_sib": "#FF2244",
    "btn_del": "#FF8800",
    "node_bg": "#231818",
    "node_border": "#FF2244",
    "node_text": "#F5E0E0",
    "toolbar_bg": "#1A1111",
    "toolbar_sep": "#FF2244",
    "toolbar_btn": "#F5E0E0",
    "toolbar_btn_h": "#FF6655",
    "sig_bg_l": "#120A0A",
    "sig_bg_r": "#1A1111",
    "sig_border": "#FF2244",
    "sig_text": "#F5E0E0",
    "btn_close_h": "#FF6655",
    "btn_win_h": "#FF8800",
    "shadow": "#080404",
    "shadow_offset_x": 8,
    "shadow_offset_y": 8,
    "shadow_hover_offset_x": 0,
    "shadow_hover_offset_y": 0,
    "border_width": 4,
    "border_radius": 0,
    "font_family": "'Playfair Display', 'Georgia', 'Segoe UI', sans-serif",
    "font_family_content": "'Playfair Display', 'Georgia', 'Segoe UI', sans-serif",
    "font_weight": 900,
    "font_uppercase": True,
    "block_yellow": "#FFD700",
    "block_green": "#44DD88",
    "block_blue": "#2288FF",
    "block_red": "#FF2244",
    "block_orange": "#FF6655",
    "block_purple": "#CC44FF",
    "block_pink": "#FF66AA",
}

# ─── 9. OCEAN: Azul marinho, espuma branca, marítimo ──────────────────

THEMES["ocean"] = {
    "name": "ocean",
    "bg_app": "#0B1E3D",
    "bg_card": "#112C52",
    "bg_card2": "#1A3A6A",
    "bg_input": "#112C52",
    "glass_border": "#FFFFFF",
    "accent": "#00B4D8",
    "accent_bright": "#90E0EF",
    "accent_dim": "#0077B6",
    "text": "#E8F4FD",
    "text_dim": "#80AAD0",
    "text_muted": "#5A8AB0",
    "line": "#00B4D8",
    "line_eap": "#90E0EF",
    "btn_add": "#2DD4BF",
    "btn_sib": "#00B4D8",
    "btn_del": "#F87171",
    "node_bg": "#1A3A6A",
    "node_border": "#00B4D8",
    "node_text": "#E8F4FD",
    "toolbar_bg": "#112C52",
    "toolbar_sep": "#00B4D8",
    "toolbar_btn": "#E8F4FD",
    "toolbar_btn_h": "#90E0EF",
    "sig_bg_l": "#0B1E3D",
    "sig_bg_r": "#112C52",
    "sig_border": "#00B4D8",
    "sig_text": "#E8F4FD",
    "btn_close_h": "#F87171",
    "btn_win_h": "#90E0EF",
    "shadow": "#050E1D",
    "shadow_offset_x": 8,
    "shadow_offset_y": 8,
    "shadow_hover_offset_x": 0,
    "shadow_hover_offset_y": 0,
    "border_width": 4,
    "border_radius": 0,
    "font_family": "'Ubuntu', 'Segoe UI', 'Helvetica', sans-serif",
    "font_family_content": "'Ubuntu', 'Segoe UI', 'Helvetica', sans-serif",
    "font_weight": 900,
    "font_uppercase": True,
    "block_yellow": "#FFC107",
    "block_green": "#2DD4BF",
    "block_blue": "#00B4D8",
    "block_red": "#F87171",
    "block_orange": "#FB923C",
    "block_purple": "#A78BFA",
    "block_pink": "#F472B6",
}

# ─── 10. VOLCANO: Preto basalto, amarelo lava, explosivo ──────────────

THEMES["volcano"] = {
    "name": "volcano",
    "bg_app": "#1A1410",
    "bg_card": "#251D16",
    "bg_card2": "#30251C",
    "bg_input": "#251D16",
    "glass_border": "#FFFFFF",
    "accent": "#F5A623",
    "accent_bright": "#FF6600",
    "accent_dim": "#8B5E1A",
    "text": "#F2E8DA",
    "text_dim": "#9E8C7A",
    "text_muted": "#7A6858",
    "line": "#F5A623",
    "line_eap": "#FF6600",
    "btn_add": "#43D95A",
    "btn_sib": "#F5A623",
    "btn_del": "#E53E3E",
    "node_bg": "#30251C",
    "node_border": "#F5A623",
    "node_text": "#F2E8DA",
    "toolbar_bg": "#251D16",
    "toolbar_sep": "#F5A623",
    "toolbar_btn": "#F2E8DA",
    "toolbar_btn_h": "#FF6600",
    "sig_bg_l": "#1A1410",
    "sig_bg_r": "#251D16",
    "sig_border": "#F5A623",
    "sig_text": "#F2E8DA",
    "btn_close_h": "#E53E3E",
    "btn_win_h": "#FF6600",
    "shadow": "#0D0A08",
    "shadow_offset_x": 8,
    "shadow_offset_y": 8,
    "shadow_hover_offset_x": 0,
    "shadow_hover_offset_y": 0,
    "border_width": 4,
    "border_radius": 0,
    "font_family": "'Barlow Condensed', 'Arial Black', 'Segoe UI', sans-serif",
    "font_family_content": "'Barlow Condensed', 'Arial Black', 'Segoe UI', sans-serif",
    "font_weight": 900,
    "font_uppercase": True,
    "block_yellow": "#F5A623",
    "block_green": "#43D95A",
    "block_blue": "#3B82F6",
    "block_red": "#E53E3E",
    "block_orange": "#FF6600",
    "block_purple": "#8B5CF6",
    "block_pink": "#EC4899",
}

# ─── 11. MINT: Verde-menta suave, creme, frescura ─────────────────────

THEMES["mint"] = {
    "name": "mint",
    "bg_app": "#EAFBF5",
    "bg_card": "#F5FFFD",
    "bg_card2": "#DFF8ED",
    "bg_input": "#F5FFFD",
    "glass_border": "#000000",
    "accent": "#00B894",
    "accent_bright": "#55E6C1",
    "accent_dim": "#00796B",
    "text": "#1A2E25",
    "text_dim": "#4F8A74",
    "text_muted": "#7FA89A",
    "line": "#00B894",
    "line_eap": "#55E6C1",
    "btn_add": "#00B894",
    "btn_sib": "#007A6A",
    "btn_del": "#E17055",
    "node_bg": "#DFF8ED",
    "node_border": "#00B894",
    "node_text": "#1A2E25",
    "toolbar_bg": "#F5FFFD",
    "toolbar_sep": "#00B894",
    "toolbar_btn": "#1A2E25",
    "toolbar_btn_h": "#55E6C1",
    "sig_bg_l": "#EAFBF5",
    "sig_bg_r": "#F5FFFD",
    "sig_border": "#00B894",
    "sig_text": "#1A2E25",
    "btn_close_h": "#E17055",
    "btn_win_h": "#55E6C1",
    "shadow": "#B0DED2",
    "shadow_offset_x": 8,
    "shadow_offset_y": 8,
    "shadow_hover_offset_x": 0,
    "shadow_hover_offset_y": 0,
    "border_width": 4,
    "border_radius": 0,
    "font_family": "'Nunito', 'Segoe UI', 'Helvetica', sans-serif",
    "font_family_content": "'Nunito', 'Segoe UI', 'Helvetica', sans-serif",
    "font_weight": 900,
    "font_uppercase": True,
    "block_yellow": "#FDCB6E",
    "block_green": "#00B894",
    "block_blue": "#0984E3",
    "block_red": "#E17055",
    "block_orange": "#F39C12",
    "block_purple": "#6C5CE7",
    "block_pink": "#FD79A8",
}

# ─── 12. ONYX: Preto absoluto, cinza grafite, ultra minimalista ───────

THEMES["onyx"] = {
    "name": "onyx",
    "bg_app": "#0A0A0A",
    "bg_card": "#141414",
    "bg_card2": "#1E1E1E",
    "bg_input": "#141414",
    "glass_border": "#FFFFFF",
    "accent": "#FFFFFF",
    "accent_bright": "#CCCCCC",
    "accent_dim": "#555555",
    "text": "#EEEEEE",
    "text_dim": "#999999",
    "text_muted": "#666666",
    "line": "#FFFFFF",
    "line_eap": "#CCCCCC",
    "btn_add": "#00E676",
    "btn_sib": "#FFFFFF",
    "btn_del": "#FF1744",
    "node_bg": "#1E1E1E",
    "node_border": "#FFFFFF",
    "node_text": "#EEEEEE",
    "toolbar_bg": "#141414",
    "toolbar_sep": "#FFFFFF",
    "toolbar_btn": "#EEEEEE",
    "toolbar_btn_h": "#CCCCCC",
    "sig_bg_l": "#0A0A0A",
    "sig_bg_r": "#141414",
    "sig_border": "#FFFFFF",
    "sig_text": "#EEEEEE",
    "btn_close_h": "#FF1744",
    "btn_win_h": "#CCCCCC",
    "shadow": "#000000",
    "shadow_offset_x": 8,
    "shadow_offset_y": 8,
    "shadow_hover_offset_x": 0,
    "shadow_hover_offset_y": 0,
    "border_width": 4,
    "border_radius": 0,
    "font_family": "'Inter', 'Helvetica Neue', 'Segoe UI', sans-serif",
    "font_family_content": "'Inter', 'Helvetica Neue', 'Segoe UI', sans-serif",
    "font_weight": 900,
    "font_uppercase": True,
    "block_yellow": "#FFD600",
    "block_green": "#00E676",
    "block_blue": "#448AFF",
    "block_red": "#FF1744",
    "block_orange": "#FF9100",
    "block_purple": "#E040FB",
    "block_pink": "#FF80AB",
}

# ─── 13. LILAC: Lavanda, malva, tonalidade delicada ───────────────────

THEMES["lilac"] = {
    "name": "lilac",
    "bg_app": "#F3EFF5",
    "bg_card": "#FFFFFF",
    "bg_card2": "#EDE5F5",
    "bg_input": "#FFFFFF",
    "glass_border": "#000000",
    "accent": "#AA00FF",
    "accent_bright": "#7C3AFF",
    "accent_dim": "#7828D8",
    "text": "#1E0030",
    "text_dim": "#5A3A70",
    "text_muted": "#8A6BA0",
    "line": "#AA00FF",
    "line_eap": "#7C3AFF",
    "btn_add": "#00C853",
    "btn_sib": "#AA00FF",
    "btn_del": "#FF1744",
    "node_bg": "#EDE5F5",
    "node_border": "#AA00FF",
    "node_text": "#1E0030",
    "toolbar_bg": "#FFFFFF",
    "toolbar_sep": "#AA00FF",
    "toolbar_btn": "#1E0030",
    "toolbar_btn_h": "#7C3AFF",
    "sig_bg_l": "#F3EFF5",
    "sig_bg_r": "#FFFFFF",
    "sig_border": "#AA00FF",
    "sig_text": "#1E0030",
    "btn_close_h": "#FF1744",
    "btn_win_h": "#7C3AFF",
    "shadow": "#B0A0C0",
    "shadow_offset_x": 8,
    "shadow_offset_y": 8,
    "shadow_hover_offset_x": 0,
    "shadow_hover_offset_y": 0,
    "border_width": 4,
    "border_radius": 0,
    "font_family": "'Poppins', 'Segoe UI', 'Helvetica', sans-serif",
    "font_family_content": "'Poppins', 'Segoe UI', 'Helvetica', sans-serif",
    "font_weight": 900,
    "font_uppercase": True,
    "block_yellow": "#FFD600",
    "block_green": "#00C853",
    "block_blue": "#2979FF",
    "block_red": "#FF1744",
    "block_orange": "#FF6D00",
    "block_purple": "#AA00FF",
    "block_pink": "#FF3CAC",
}

# Estado global do tema: dicionário mutável que armazena tema ativo.
_ACTIVE = {"theme": THEMES["neo_brutalist"]}

# Sequência de rotação de temas (13 temas).
_THEME_ORDER = [
    "neo_brutalist",
    "midnight",
    "embers",
    "forest",
    "synthwave",
    "arctic",
    "solar",
    "crimson",
    "ocean",
    "volcano",
    "mint",
    "onyx",
    "lilac",
]


def T():
    # Retorna dicionário do tema ativo.
    return _ACTIVE["theme"]


def set_theme(name: str):
    # Define tema ativo pelo nome.
    _ACTIVE["theme"] = THEMES[name]


def cycle_theme():
    # Avança para o próximo tema na sequência de 7 temas.
    current = _ACTIVE["theme"]["name"]
    if current in _THEME_ORDER:
        idx = _THEME_ORDER.index(current)
        nxt = _THEME_ORDER[(idx + 1) % len(_THEME_ORDER)]
        _ACTIVE["theme"] = THEMES[nxt]
        return nxt


# Mapeamento de cores para nós do diagrama 5W2H.
W5H2_TYPES = {
    "ROOT": {"t": "PLANO DE ACAO", "c": "#E03535"},
    "WHAT": {"t": "O QUE? (Acao)", "c": "#3498DB"},
    "WHY": {"t": "POR QUE? (Justificativa)", "c": "#F1C40F"},
    "WHO": {"t": "QUEM? (Responsavel)", "c": "#9B59B6"},
    "WHERE": {"t": "ONDE? (Local)", "c": "#2ECC71"},
    "WHEN": {"t": "QUANDO? (Prazo)", "c": "#E67E22"},
    "HOW": {"t": "COMO? (Metodo/Etapas)", "c": "#1ABC9C"},
    "COST": {"t": "QUANTO? (Custo/Orcamento)", "c": "#E74C3C"},
}
